Update UG
AY2223S1-CS2103T-T11-3/tp pull request #106
Opened 2022-10-25 17:32 UTC by fongyj

- Update UG for all commands
- Update some javadocs
- Update HelpCommand and ClearCommand

2022-10-25 17:38 UTC, fongyj commented on docs/UserGuide.md
> +Action | Format                                                           | Examples
It seems like in the original AB3 UG this table is sorted alphabetically, but I just put it according to the order above. Not sure if it has to be sorted alphabetically.

2022-10-25 18:10 UTC, laxus2308 requested changes
Thanks for helping to update the UG! I spot some minor issues to make the style more consistent, and I think we should include in the command format how the format of deadline, date and time will be in our commands.

2022-10-25 18:10 UTC, laxus2308 commented on docs/UserGuide.md
> +* `addpart p/100 li/1 si/2` sets participation for the 2nd student from the 1st lesson to be 100.
i think we should specify that the `Lesson` here must be a `Studio`, if for example `Mastery Check` is provided as LESSON_INDEX, the command will not work. 
```suggestion
### Adding participation for a student in a lesson : `addpart`

Adds participation for a student in a lesson.

Format: `addpart p/PARTICIPATION li/LESSON_INDEX si/STUDENT_INDEX`

* `PARTICIPATION` **must be a positive integer** from 0 to 500.
* `LESSON_INDEX` refers to the index number shown in the displayed list of tasks.
* `STUDENT_INDEX` refers to the index number shown in the student list for the specified lesson. (use `listlesson` to view the student list for lessons)
* `LESSON_INDEX` and `STUDENT_INDEX` **must be a positive integer** 1, 2, 3, …​

Example:
* `addpart p/100 li/1 si/2` sets participation for the 2nd student from the 1st lesson to be 100.
```

2022-10-25 18:10 UTC, laxus2308 commented on src/main/java/jarvis/logic/commands/AddParticipationCommand.java
> +            + "specified lesson\n"
```suggestion
            + ": Adds participation for a student in a studio. The studio is identified by its index number in the"
            + " displayed lesson list. The student is identified using its displayed index in the student list of the "
            + "specified studio\n"
```

2022-10-25 18:10 UTC, laxus2308 commented on docs/UserGuide.md
> +**Add participation** | `addpart p/PARTICIPATION li/LESSON INDEX si/STUDENT_INDEX` |  `addpart p/100 li/1 si/2`
missing the _ for some 

```suggestion
**Unmark student** | `unmarkstudent li/LESSON_INDEX si/STUDENT_INDEX` | `unmarkstudent li/2 si/3`
**Add note** | `addnote n/NOTE li/LESSON_INDEX [si/STUDENT_INDEX]` | `addnote n/Get back to jeff on streams li/1 si/2`
**Delete note** | `deletenote ni/NOTE_INDEX li/LESSON_INDEX [si/STUDENT_INDEX]` | `deletenote ni/1 li/1 si/2`
**Add participation** | `addpart p/PARTICIPATION li/LESSON_INDEX si/STUDENT_INDEX` |  `addpart p/100 li/1 si/2`
```

2022-10-25 18:10 UTC, laxus2308 commented on docs/UserGuide.md
> +Format: `addnote n/NOTE li/LESSON INDEX [si/STUDENT_INDEX]`
```suggestion
Format: `addnote n/NOTE li/LESSON_INDEX [si/STUDENT_INDEX]`
```

2022-10-25 18:10 UTC, laxus2308 commented on docs/UserGuide.md
> +Format: `deletenote ni/NOTE INDEX li/LESSON INDEX [si/STUDENT_INDEX]`
```suggestion
Format: `deletenote ni/NOTE_INDEX li/LESSON_INDEX [si/STUDENT_INDEX]`
```

2022-10-25 18:10 UTC, laxus2308 commented on src/main/java/jarvis/logic/commands/UnmarkStudentCommand.java
>              + PREFIX_LESSON_INDEX + "LESSON INDEX "
```suggestion
            + PREFIX_LESSON_INDEX + "LESSON_INDEX "
```

2022-10-26 01:51 UTC, neosunhan requested changes

2022-10-26 01:51 UTC, neosunhan commented on docs/UserGuide.md
> +  e.g `t/TASK_DESC [d/DEADLINE]` can be used as `t/Mark quest 2 d/23-09-2023` or as `t/Mark quest 2`.
Task deadline should be in yyyy-MM-dd format

2022-10-26 01:51 UTC, neosunhan commented on docs/UserGuide.md
> +### Adding a student: `addstudent`
I think we can include a line that says that you can only add up to 10 students

2022-10-26 01:51 UTC, neosunhan commented on docs/UserGuide.md
> +*  `editstudent 1 s/John Do` edits the name the 1st student to be `John Do`
```suggestion
*  `editstudent 1 s/John Do` edits the name of the 1st student to be `John Do`
```

2022-10-26 05:36 UTC, rycs2812 requested changes
A few typos but everything is good apart from that

2022-10-26 05:36 UTC, rycs2812 commented on docs/UserGuide.md
> +* `addstudent s/Alex Yeoh m/A012345A`
Matric number here is missing a digit

2022-10-26 05:36 UTC, rycs2812 commented on docs/UserGuide.md
> +Format: `edit INDEX [s/NAME] [m/MATRIC_NUM]`
Change to editstudent

2022-10-26 05:36 UTC, rycs2812 commented on docs/UserGuide.md
>  Format: `find KEYWORD [MORE_KEYWORDS]`
Change to findstudent

2022-10-26 05:36 UTC, rycs2812 commented on docs/UserGuide.md
>  * `find John` returns `john` and `John Doe`
Change to findstudent

2022-10-26 05:36 UTC, rycs2812 commented on docs/UserGuide.md
> +* `ed/END_DATE` is optional, if unspecified `END_DATE` will be assumed to be the same as START_DATE
Might be better to use inline code for START_DATE to be consistent i.e. change to `START_DATE`

2022-10-26 05:36 UTC, rycs2812 commented on docs/UserGuide.md
> +* `ed/END_DATE` is optional, if unspecified `END_DATE` will be assumed to be the same as START_DATE
Same as above, change to `START_DATE`

2022-10-26 05:36 UTC, rycs2812 commented on docs/UserGuide.md
> +* `PARTICIPATION` **must be a positive integer** from 0 to 500.
Change "positive integer" to "non-negative integer"

2022-10-26 05:36 UTC, rycs2812 commented on docs/UserGuide.md
> +**Find student** | `find KEYWORD [MORE_KEYWORDS]`                                                                    | `find John`
Change to editstudent and findstudent

2022-10-26 06:30 UTC, rycs2812 approved these changes
LGTM

2022-10-26 09:19 UTC, merged