Add tests for delete and clear commands
AY2223S1-CS2103T-T11-3/tp pull request #148
Opened 2022-10-30 09:55 UTC by laxus2308

- Add in Task util classes for testing
- Add task test
- Add task description test
- Add task deadline test
- Add student matric number test
- Refactor deleteStudentCommandTest
- Add deleteTaskCommandTest

2022-11-01 11:19 UTC, neosunhan commented on src/test/java/jarvis/model/student/StudentMatricNumTest.java
> +        assertTrue(MatricNum.isValidMatricNum("A1234567A")); // numbers only
What do these comments mean?

2022-11-01 11:19 UTC, neosunhan commented on src/test/java/jarvis/model/student/StudentMatricNumTest.java
> +    }
I think you forgot to test this?

2022-11-07 04:14 UTC, fongyj requested changes

2022-11-07 04:14 UTC, fongyj commented on src/test/java/jarvis/logic/commands/AddMasteryCheckCommandTest.java
> +        //valid masteryCheck with diff desc but same time period
```suggestion
        // valid masteryCheck with diff desc but same time period
```

2022-11-07 04:14 UTC, fongyj commented on src/test/java/jarvis/logic/commands/AddStudioCommandTest.java
> +        //valid studio with diff desc but same time period
```suggestion
        // valid studio with diff desc but same time period
```

2022-11-07 04:14 UTC, fongyj commented on src/test/java/jarvis/logic/commands/AddConsultCommandTest.java
> +        //valid consult with diff desc but same time period
```suggestion
        // valid consult with diff desc but same time period
```

2022-11-07 04:14 UTC, fongyj commented on src/test/java/jarvis/logic/commands/DeleteTaskCommandTest.java
> +    //    }
did you forget to delete this

2022-11-07 04:14 UTC, fongyj commented on src/test/java/jarvis/model/StudentMatricNumTest.java
> +        //same values -> returns true
```suggestion
        // same values -> returns true
```

2022-11-07 04:14 UTC, fongyj commented on src/test/java/jarvis/model/StudentMatricNumTest.java
> +        //same object -> returns true
```suggestion
        // same object -> returns true
```

2022-11-07 04:14 UTC, fongyj commented on src/test/java/jarvis/model/StudentMatricNumTest.java
> +        //different values -> returns false
```suggestion
        // different values -> returns false
```

2022-11-07 04:14 UTC, fongyj commented on src/test/java/jarvis/model/TaskDescTest.java
> +        assertFalse(desc1.equals(desc2));
```suggestion
        // same values -> returns true
        TaskDesc desc1Copy = new TaskDesc("desc1");
        assertTrue(desc1.equals(desc1Copy));

        // same object -> returns true
        assertTrue(desc1.equals(desc1));

        // null -> returns false
        assertFalse(desc1.equals(null));

        // different type -> returns false
        assertFalse(desc1.equals(5));

        // different values -> returns false
        assertFalse(desc1.equals(desc2));
```

2022-11-07 04:14 UTC, fongyj commented on src/test/java/jarvis/model/TaskDeadlineTest.java
> +        assertFalse(deadline1.equals(deadline2));
```suggestion
        // same values -> returns true
        TaskDeadline deadline1Copy = new TaskDeadline(date1);
        assertTrue(deadline1.equals(deadline1Copy));

        // same object -> returns true
        assertTrue(deadline1.equals(deadline1));

        // null -> returns false
        assertFalse(deadline1.equals(null));

        // different type -> returns false
        assertFalse(deadline1.equals(5));

        // different values -> returns false
        assertFalse(deadline1.equals(deadline2));
```

2022-11-07 04:14 UTC, fongyj commented on src/test/java/jarvis/model/TaskTest.java
> +        assertEquals(expectedDeadline, taskWithDeadline.getDeadlineString());
```suggestion
    public void getDeadline() {
        // no deadline
        Task taskWithoutDeadline = new TaskBuilder().withoutDeadline().build();
        assertEquals(null, taskWithoutDeadline.getDeadline());

        // correct deadline
        Task taskWithDeadline = new TaskBuilder().withDeadline(VALID_TASK_DEADLINE).build();
        assertEquals(VALID_TASK_DEADLINE, taskWithDeadline.getDeadline());
    }

    @Test
    public void getDeadlineString() {
        // no deadline
        Task taskWithoutDeadline = new TaskBuilder().withoutDeadline().build();
        assertEquals("", taskWithoutDeadline.getDeadlineString());

        // has deadline
        Task taskWithDeadline = new TaskBuilder().withDeadline(VALID_TASK_DEADLINE).build();
        String expectedDeadline = VALID_TASK_DEADLINE.format(DateTimeFormatter.ofPattern("MMM-dd-yyyy"));
        assertEquals(expectedDeadline, taskWithDeadline.getDeadlineString());
```

2022-11-07 04:14 UTC, fongyj commented on src/test/java/jarvis/model/TaskTest.java
> +        assertFalse(newTask.isDone()); //task that is not done remains not done
```suggestion
        assertFalse(newTask.isDone()); // task that is not done remains not done
```

2022-11-07 04:45 UTC, fongyj approved these changes
LGTM

2022-11-07 04:45 UTC, merged